/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zakator;

/**
 *
 * @author windows
 */
public class Fitrah extends javax.swing.JFrame {

    /**
     * Creates new form Fitrah
     */
    int orang, harga_beras, jml_uang;
    double jml_beras;
    
    public Fitrah() {
        initComponents();
        jLcek.setVisible(false);
        jLcek2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTorang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTharga_beras = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLuang = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLberas = new javax.swing.JLabel();
        jLcek = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLcek2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Zakat Fitrah");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 380, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jumlah Orang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 380, -1));

        jTorang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTorangActionPerformed(evt);
            }
        });
        jTorang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTorangKeyTyped(evt);
            }
        });
        getContentPane().add(jTorang, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 74, 77, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Harga Beras 1Kg Saat ini");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, -1));

        jTharga_beras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTharga_berasActionPerformed(evt);
            }
        });
        getContentPane().add(jTharga_beras, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 124, 77, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Zakat Fitrah Yang Harus Ditunaikan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 380, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("Dalam Uang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 179, -1, -1));

        jLuang.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLuang.setText("-");
        getContentPane().add(jLuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 179, 186, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Atau");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 203, 71, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("Dalam Beras");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 227, -1, -1));

        jLberas.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLberas.setText("-");
        getContentPane().add(jLberas, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 227, 110, -1));

        jLcek.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLcek.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLcek, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 70, 150, 30));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton1.setText("Hitung Zakat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 263, -1, -1));

        jLcek2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLcek2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLcek2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 150, 30));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 263, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zakator/13081-01-gradient-designs-powerpoint-backgrounds-16x9-1.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTharga_berasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTharga_berasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTharga_berasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!jTorang.getText().matches("[0-9]*")){
            jLcek.setText("Masukan harus angka"); 
            jLcek.setVisible(true);
        }else {
            jLcek.setVisible(false);
        }
        
        if (!jTharga_beras.getText().matches("[0-9]*")){
            jLcek2.setText("Masukan harus angka"); 
            jLcek2.setVisible(true);
        }else {
            jLcek2.setVisible(false);
        }
        orang = Integer.parseInt(jTorang.getText());
        harga_beras = Integer.parseInt(jTharga_beras.getText());
        
        jml_beras = orang*2.5;
        jLberas.setText(""+Double.toString(jml_beras)+"Kg");
        
        jml_uang = (int) (orang*harga_beras*2.5);
        jLuang.setText("Rp. "+Integer.toString(jml_uang)+",00");  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTorangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTorangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTorangActionPerformed

    private void jTorangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTorangKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTorangKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fitrah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fitrah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fitrah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fitrah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fitrah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLberas;
    private javax.swing.JLabel jLcek;
    private javax.swing.JLabel jLcek2;
    private javax.swing.JLabel jLuang;
    private javax.swing.JTextField jTharga_beras;
    private javax.swing.JTextField jTorang;
    // End of variables declaration//GEN-END:variables
}
