/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zakator;

/**
 *
 * @author windows
 */
public class Tabungan extends javax.swing.JFrame {

    /**
     * Creates new form Tabungan
     */
    int pilihan, harga, kekayaan, nisab, hasil;
    double logam;
    
    public Tabungan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCnisab = new javax.swing.JComboBox<>();
        jTharga = new javax.swing.JTextField();
        jLharga = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTkekayaan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLhasil = new javax.swing.JLabel();
        jLket = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Zakat Maal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 391, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Harta Kekayaan atau Tabungan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 391, -1));

        jLabel3.setText("Menentukan Nisab");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 74, 111, -1));

        jLabel4.setText("Jenis Harta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 119, 110, -1));

        jCnisab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tabungan", "Emas", "Perak" }));
        jCnisab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCnisabActionPerformed(evt);
            }
        });
        getContentPane().add(jCnisab, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 139, 110, -1));
        getContentPane().add(jTharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 196, 67, -1));

        jLharga.setText("Harga Emas saat ini :");
        getContentPane().add(jLharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 170, 130, -1));

        jLabel6.setText("/Gram");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 199, 39, -1));

        jLabel7.setText("*Harta harus dimiliki selama 1 tahun");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 94, -1, -1));

        jLabel8.setText("Jumlah Kekayaan Anda");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 106, 141, 27));

        jTkekayaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTkekayaanActionPerformed(evt);
            }
        });
        getContentPane().add(jTkekayaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 139, 141, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Zakat Yang Harus Anda Tunaikan Adalah");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, 391, -1));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton1.setText("Hitung Zakat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 294, 120, -1));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 294, -1, -1));

        jLhasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLhasil.setText("Rp.- ");
        getContentPane().add(jLhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 391, -1));

        jLket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, 391, 21));

        jLabel5.setText("*masukkan dalam gram untuk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 170, -1, -1));

        jLabel10.setText(" emas dan perak");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 190, 141, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zakator/13081-01-gradient-designs-powerpoint-backgrounds-16x9-1.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCnisabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCnisabActionPerformed
        // TODO add your handling code here:
        pilihan = jCnisab.getSelectedIndex();
        
        if(pilihan==0){
            jLharga.setText("Harga Emas Saat Ini:");
        }else if (pilihan==1){
            jLharga.setText("Tidak perlu diisi:");
            jTharga.setText("1");
        }else{
            jLharga.setText("Tidak perlu diisi:");
            jTharga.setText("1");
        }
        
    }//GEN-LAST:event_jCnisabActionPerformed

    private void jTkekayaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTkekayaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTkekayaanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pilihan = jCnisab.getSelectedIndex();
        harga = Integer.parseInt(jTharga.getText());
        kekayaan = Integer.parseInt(jTkekayaan.getText());
        
        if (pilihan == 0){
            nisab = harga*85;
            if (nisab<=kekayaan){
                hasil = (int) (2.5/100*kekayaan);
                jLhasil.setText("Rp. "+hasil+",00");
                jLket.setText("");
            }else {
                jLhasil.setText("Anda tidak wajib membayar Zakar Maal");
                jLket.setText("Karena kekayaan anda kurang dari Nisab, yaitu Rp."+Integer.toString(nisab)+",00");
        }
        }else if (pilihan == 1){
            nisab = harga*85;
            if (nisab<=kekayaan){
                logam = (double)(2.5/100*kekayaan);
                jLhasil.setText(logam+" Gram emas");
                jLket.setText("");
            }else{
                jLhasil.setText("Anda tidak wajib membayar Zakar Maal");
                jLket.setText("Karena kekayaan anda kurang dari Nisab, yaitu "+Integer.toString(nisab)+" Gram emas");
            }
        }else{
            nisab = 595;
            if (nisab<=kekayaan){
                logam = (double)(2.5/100*kekayaan);
                jLhasil.setText(logam+" Gram perak");
                jLket.setText("");
            }else {
                jLhasil.setText("Anda tidak wajib membayar Zakar Maal");
                jLket.setText("Karena kekayaan anda kurang dari Nisab, yaitu "+Integer.toString(nisab)+" Gram perak");
        }
        }                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Maal maal = new Maal();
        maal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabungan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCnisab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLharga;
    private javax.swing.JLabel jLhasil;
    private javax.swing.JLabel jLket;
    private javax.swing.JTextField jTharga;
    private javax.swing.JTextField jTkekayaan;
    // End of variables declaration//GEN-END:variables
}
